# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", 3.11, 3.12, 3.13]
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Test with tox
      run: |
        poetry install
        poetry update
        source .venv/bin/activate
        tox


    - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11
      uses: codecov/codecov-action@v3
      if: ${{ matrix.python-version == '3.11' }}
      with:
        file: ./coverage.xml
